services:
  skin-lesion-api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: skin-lesion-api
    ports:
     - "8484:8484"

  skin-lesion-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: skin-lesion-frontend
    ports:
      - "3000:80"
    depends_on:
      - skin-lesion-api
